### ISSUE TITLE
Issue with approval page

### ISSUE THREAD

**Issue by jwillenbring** [CIgathi/NDSU-Thesis-Class#1]
Hello,

I want to thank you first for creating this template. When I completed my MS, the school I graduated from did not have a LaTeX template like this and it was a LOT of work to get things right. I cloned your template a year or two ago (23 commits back) and went with that, never updating. I ran into only one small formatting issue that was related to the general document formatting. The issue was that on the approval page my title was double spaced, but it was supposed to be single spaced. To remedy that, I changed the code in the cls file slightly.

I had to change the cls file to single space the title on the approval page and then return to double spacing for the author. Specifically I added the "\singlespacing" and then later had to add "\doublespacing" to avoid formatting errors associate with having my name single spaced with the author heading. I recognize fully this was not the most elegant way to do this. I also went in and noticed that the code in this area has changed, so you may have addressed this in a different way already. In both the older and newer versions, this was after line 400 in the cls file. I apologize for the vagueness of this report. If you need more specific line numbers or more details let me know. I wanted to get this checked off because I have a very busy day today but didn't want this to slip. You may know off the top of your head that this issue has already been addressed. Thanks again for the great starting point.  

...
        \begin{center}
        \textbf{Title} \\
        \singlespacing
        \@title
        \vspace{.2in}
        \hrule
        \vspace{.2in}
        \textbf{By} \\
        \doublespacing\@author
        \vspace{.2in}
...

**Comment by CIgathi** [comment]
Hello James:

Thanks for your interest. Will you give some background information about you, and your school? Do you want to adopt and modify the NDSU template to suit your school’s thesis style? There may be several items that have to be modified to make your school thesis look unique. Line numbering is already included - you may check the extensive documentation (two styles) I prepared and uploaded to GitHub. The newest version is in the GitHub (https://github.com/CIgathi/NDSU-Thesis-Class).

The idea of changing the title page spacing as described is one way to go about it - and if it works then good and should move on to others.

As you know with LaTeX, anything is possible. Your thoughts!

Thanks,

C. Igathi
----------------------------------------------------------------------------------------------------------------------------------------------------------
Igathinathane (Igathi) Cannayen, Ph.D.                                             Office:
Associate Professor  /  Agricultural and Biosystems Engineering      Northern Great Plains Research Lab
ABEN Graduate Program Coordinator                                               USDA-ARS / Room 208 / 1701 10th Avenue SW
NORTH DAKOTA STATE UNIVERSITY                                             PO Box 459 / Mandan ND 58554-0459
Dept 7620, PO Box 6050  /  Fargo ND 58108-6050
p: 701.667.3011  /  f: 701-667-3054
***@***.******@***.***>  /  ***@***.******@***.***>
https://www.ndsu.edu/aben/faculty_staff/dr_igathinathane_cannayen/

[cid:FE5D4169-A661-45B6-B733-43A96000CA6F]

On Jun 11, 2024, at 8:35 AM, James Willenbring ***@***.******@***.***>> wrote:



Hello,

I want to thank you first for creating this template. When I completed my MS, the school I graduated from did not have a LaTeX template like this and it was a LOT of work to get things right. I cloned your template a year or two ago (23 commits back) and went with that, never updating. I ran into only one small formatting issue that was related to the general document formatting. The issue was that on the approval page my title was double spaced, but it was supposed to be single spaced. To remedy that, I changed the code in the cls file slightly.

I had to change the cls file to single space the title on the approval page and then return to double spacing for the author. Specifically I added the "\singlespacing" and then later had to add "\doublespacing" to avoid formatting errors associate with having my name single spaced with the author heading. I recognize fully this was not the most elegant way to do this. I also went in and noticed that the code in this area has changed, so you may have addressed this in a different way already. In both the older and newer versions, this was after line 400 in the cls file. I apologize for the vagueness of this report. If you need more specific line numbers or more details let me know. I wanted to get this checked off because I have a very busy day today but didn't want this to slip. You may know off the top of your head that this issue has already been addressed. Thanks again for the great starting point.

...
\begin{center}
\textbf{Title} \
\singlespacing
@title<https://github.com/title>
\vspace{.2in}
\hrule
\vspace{.2in}
\textbf{By} \
***@***.***
\vspace{.2in}
...

**Comment by jwillenbring** [comment]
Sorry I was unclear. I just had the formatting accepted for my NDSU Ph.D. Dissertation yesterday. My MS I did not do at NDSU. The only feedback I got related to the template when I submitted for NDSU format review was incorrect spacing of my title on the approval page. This is the minor change to the cls file that I referenced. I submitted the ticket in case modifying the cls file might be useful to future NDSU students.

**Comment by CIgathi** [comment]
Are you an NDSU student? This is not clear. 

Anyhow, several theses were approved using the previous template. I based the LaTeX class on the official MS Word template of NDSU. NDSU does not maintain LaTeX template, what I have is my voluntary work and students can use it if they like. I will look into the spacing issues you mentioned and update as appropriate.  Thanks for your input. 

Thanks,

C. Igathi
----------------------------------------------------------------------------------------------------------------------------------------------------------
Igathinathane (Igathi) Cannayen, Ph.D.                                             Office:     
Associate Professor  /  Agricultural and Biosystems Engineering      Northern Great Plains Research Lab 
ABEN Graduate Program Coordinator                                               USDA-ARS / Room 208 / 1701 10th Avenue SW
NORTH DAKOTA STATE UNIVERSITY                                             PO Box 459 / Mandan ND 58554-0459  
Dept 7620, PO Box 6050  /  Fargo ND 58108-6050    
p: 701.667.3011  /  f: 701-667-3054    
***@***.***  /  ***@***.***
https://www.ndsu.edu/aben/faculty_staff/dr_igathinathane_cannayen/

**Comment by jwillenbring** [comment]
Yes, I am an NDSU student. Sorry for the confusion. Thanks.

**Comment by CIgathi** [comment]
Hello James:

I have updated the GitHub repository. Thanks for noticing and bringing this up. As proof, the extended thesis which had a long title now compiles like this:




While the cover page retains the double spacing. 



Such feedback improves the utility of the class. Appreciate your interest. 

Thanks,

C. Igathi
----------------------------------------------------------------------------------------------------------------------------------------------------------
Igathinathane (Igathi) Cannayen, Ph.D.                                             Office:     
Associate Professor  /  Agricultural and Biosystems Engineering      Northern Great Plains Research Lab 
ABEN Graduate Program Coordinator                                               USDA-ARS / Room 208 / 1701 10th Avenue SW
NORTH DAKOTA STATE UNIVERSITY                                             PO Box 459 / Mandan ND 58554-0459  
Dept 7620, PO Box 6050  /  Fargo ND 58108-6050    
p: 701.667.3011  /  f: 701-667-3054    
***@***.***  /  ***@***.***
https://www.ndsu.edu/aben/faculty_staff/dr_igathinathane_cannayen/

**Comment by jwillenbring** [comment]
Thanks.
